name: PR opened/synchronize

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - '**.md'

  workflow_dispatch:

jobs:
  pr-open-sync:
    uses: ./.github/workflows/ci.yml
    with:
      message: 'PR opened/synchronized'
