name: PR open/sync

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - '**.md'

jobs:
  pr-open-sync:
    uses: ./.github/workflows/ci.yml
    with:
      message: 'PR opened/synchroized'
