name: PR edited

on:
  pull_request:
    types:
      - edited
    branches:
      - main

  workflow_dispatch:

jobs:
  pr-edited:
    uses: ./.github/workflows/ci.yml
    with:
      message: 'PR edited'
