name: CI

on:
  workflow_call:
    inputs:
      message:
        type: string
        description: custom message
        required: true

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        if: ${{ inputs.message }}
        env:
          MESSAGE: ${{ inputs.message }}
        run: |
          echo "message: $MESSAGE"
